name: ci

on:
  push:
    branches:
      - master
  pull_request:

env:
  TEST_TAG: tandav/centos6-lightgbm:test
  LATEST_TAG: tandav/centos6-lightgbm:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://docs.docker.com/build/ci/github-actions/examples/#test-your-image-before-pushing-it

      - name: Build test Docker image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.TEST_TAG }}
      
      - name: test lightgbm works 
        run: docker run --rm -v $PWD:/app --workdir /app ${{ env.TEST_TAG }} python train_model.py

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}
