name: ci

on:
  push:
    branches:
      - master
  pull_request:

env:
  TAG_PREFIX: tandav/centos6-lightgbm
  # TEST_TAG: tandav/centos6-lightgbm:test
  # LATEST_TAG: tandav/centos6-lightgbm:latest
  # SHA_TAG: tandav/centos6-lightgbm:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://docs.docker.com/build/ci/github-actions/examples/#test-your-image-before-pushing-it

      - name: Build test Docker image
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ env.TAG_PREFIX }}:test
      
      - name: test lightgbm works 
        run: docker run --rm -v $PWD:/app --workdir /app ${{ env.TAG_PREFIX }}:test python train_model.py

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.TAG_PREFIX }}:$GITHUB_SHA,${{ env.TAG_PREFIX }}:latest
